const TYPES = {
  SERVER: Symbol.for('SERVER'),
  HTTP_ROUTER: Symbol.for('HTTP_ROUTER'),

  TODO_ROUTER: Symbol.for('TODO_ROUTER'),
  TODO_MAPPER: Symbol.for('TODO_MAPPER'),
  TODO_REPOSITORY: Symbol.for('TODO_REPOSITORY'),

  FIND_TODOS_CONTROLLER: Symbol.for('FIND_TODOS_CONTROLLER'),
  FIND_TODOS_SERVICE: Symbol.for('FIND_TODOS_SERVICE'),

  CREATE_TODO_CONTROLLER: Symbol.for('CREATE_TODO_CONTROLLER'),
  CREATE_TODO_SERVICE: Symbol.for('CREATE_TODO_SERVICE'),
}

export { TYPES }
