version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ddh
    volumes:
      - ddh-postgres:/var/lib/postgresql/data
    # networks:
    #   - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    # networks:
    #   - postgres

  redis:
    container_name: ddd_forum_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

# networks:
#   postgres:
#     driver: bridge

volumes:
  ddh-postgres:
