export const MESSAGE_TYPES = {
  MAPPER: Symbol('MESSAGE_MAPPER'),
  QUERY_MAPPER: Symbol('MESSAGE_QUERY_MAPPER'),
  REPOSITORY: Symbol('MESSAGE_REPOSITORY'),
  QUERY_REPOSITORY: Symbol('MESSAGE_QUERY_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol('MESSAGE_SEQUELIZE_MODEL'),
}
