
### GET LIST
GET http://localhost:8086/api/v1/todos?page=1&limit=10
Content-Type: application/json

{
    "completed": false
}

### GET ONE
GET http://localhost:8086/api/v1/todos/8fed232a-1870-4635-958f-53314a0a3149

### CREATE ONE
POST http://localhost:8086/api/v1/todos/
Content-Type: application/json

{
    "text": "new todo"
}

### UPDATE ONE
PUT http://localhost:8086/api/v1/todos/8fed232a-1870-4635-958f-53314a0a3149
Content-Type: application/json

{
    "completed": true
}

### DELETE ONE
DELETE http://localhost:8086/api/v1/todos/8fed232a-1870-4635-958f-53314a0a3149

