const TODO_TYPES = {
  ROUTER: Symbol.for('TODO_ROUTER'),
  MAPPER: Symbol.for('TODO_MAPPER'),
  REPOSITORY: Symbol.for('TODO_REPOSITORY'),
  TODO_SEQUELIZE_MODEL: Symbol.for('TODO_SEQUELIZE_MODEL'),

  // FIND_TODOS_CONTROLLER: Symbol.for('FIND_TODOS_CONTROLLER'),
  FIND_TODOS_SERVICE: Symbol.for('FIND_TODOS_SERVICE'),

  // FIND_TODO_CONTROLLER: Symbol.for('FIND_TODO_CONTROLLER'),
  FIND_TODO_SERVICE: Symbol.for('FIND_TODO_SERVICE'),

  // CREATE_TODO_CONTROLLER: Symbol.for('CREATE_TODO_CONTROLLER'),
  CREATE_TODO_SERVICE: Symbol.for('CREATE_TODO_SERVICE'),

  // UPDATE_TODO_CONTROLLER: Symbol.for('UPDATE_TODO_CONTROLLER'),
  UPDATE_TODO_SERVICE: Symbol.for('UPDATE_TODO_SERVICE'),

  // DELETE_TODO_CONTROLLER: Symbol.for('DELETE_TODO_CONTROLLER'),
  DELETE_TODO_SERVICE: Symbol.for('DELETE_TODO_SERVICE'),
}

export { TODO_TYPES }
