### CREATE
POST http://localhost:8086/api/v1/posts/slug4/comments/
Content-Type: application/json

{
    "parentId": "80b3344c-c498-4737-938b-c2b53c984f77",
    "text": "child child"
}
### UPDATE BY ID
PATCH http://localhost:8086/api/v1/posts/slug-test/comments/80b3344c-c498-4737-938b-c2b53c984f77
Content-Type: application/json

{
    "text": "hello, world!!! 09.10.23 UPDATED1"
}

### DELETE BY ID
DELETE http://localhost:8086/api/v1/posts/slug-test/comments/80b3344c-c498-4737-938b-c2b53c984f77

### UPVOTE/DOWNVOTE /upvote /downvote
POST http://localhost:8086/api/v1/posts/slug-test/comments/80b3344c-c498-4737-938b-c2b53c984f77/upvote
#authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJ2aXRhbGlpQHJ1Ymljb24uY29tIiwiaWF0IjoxNjk5ODg1ODMzLCJleHAiOjE2OTk4OTMwMzN9.5xBNMHrZURisrUPGsVYwfAIEZ1BXTQrVYtrQTyRNxew


### UPVOTE/DOWNVOTE /upvote /downvote
POST http://localhost:8086/api/v1/posts/slug-test/comments/80b3344c-c498-4737-938b-c2b53c984f77/downvote


router.post('/setting', authMiddleware(true), cabinetController.setting.bind(cabinetController))
router.get('/posts', authMiddleware(true), postController.getAllByAuthUser.bind(postController))
router.get('/posts/:postId', authMiddleware(true), postController.getByAuthUser.bind(postController))


router.post('/role', adminController.addRole.bind(adminController))
router.post('/users/:userId/setRole', authMiddleware(true), adminController.setRole.bind(adminController))
router.get('/users/:userId/loginAsUser', authMiddleware(true), adminController.loginAsUser.bind(adminController))

