### GET COMMENTS BY POST SLUG
GET http://localhost:8086/api/v1/posts/slug-test/comments

### GET BY ID
GET  http://localhost:8086/api/v1/posts/slug-test/comments/c039b8d5-5528-49f6-a5bb-8155f1541c8f

### CREATE
POST http://localhost:8086/api/v1/posts/slug-test/comments/
Content-Type: application/json

{
    "text": "hello, world!!! comment with parentId"
}
### UPDATE BY ID
PATCH http://localhost:8086/api/v1/posts/slug-test/comments/f653f5cf-71fe-4f89-94d0-f6a25ccc178b
Content-Type: application/json

{
    "text": "hello, world!!! 09.10.23 UPDATED1"
}

### DELETE BY ID
DELETE http://localhost:8086/api/v1/posts/slug-test/comments/22631e6b-089a-4e81-aa2f-d1948fb671d3

### UPVOTE/DOWNVOTE /upvote /downvote
POST http://localhost:8086/api/v1/posts/slug-test/comments/efcf41a9-9bcc-4988-bc1e-762027eeb16e/upvote

### UPVOTE/DOWNVOTE /upvote /downvote
POST http://localhost:8086/api/v1/posts/slug-test/comments/efcf41a9-9bcc-4988-bc1e-762027eeb16e/downvote




///admin context 
router.post('/role', adminController.addRole.bind(adminController))
router.post('/users/:userId/setRole', authMiddleware(true), adminController.setRole.bind(adminController))
router.get('/users/:userId/loginAsUser', authMiddleware(true), adminController.loginAsUser.bind(adminController))

router.post('/setting', authMiddleware(true), cabinetController.setting.bind(cabinetController))
router.get('/posts', authMiddleware(true), postController.getAllByAuthUser.bind(postController))
router.get('/posts/:postId', authMiddleware(true), postController.getByAuthUser.bind(postController))
