### GET AUTH MEMBER 
GET http://localhost:8086/api/v1/members/currentMember


### GET MEMBER BY LOGIN
GET http://localhost:8086/api/v1/members/victor

### GET POSTS BY LOGIN
GET http://localhost:8086/api/v1/members/vitalii/posts