
### GET LIST
GET http://localhost:8086/api/v1/posts


### GET POPULAR
GET http://localhost:8086/api/v1/posts?order=popular


### GET RECENT
GET http://localhost:8086/api/v1/posts/?order=recent


### GET BY SLUG
GET http://localhost:8086/api/v1/posts/slug-test

### GET COMMENTS
GET http://localhost:8086/api/v1/posts/slug-test/comments

### UPVOTE
POST http://localhost:8086/api/v1/posts/slug-test/upvote

### DOWNVOTE
POST http://localhost:8086/api/v1/posts/slug-test/downvote

### CREATE ONE
POST http://localhost:8086/api/v1/posts/
Content-Type: application/json

{
    "title": "NEW POST",
    "text": "Text post",
    "type": "text"
}

