
### GET LIST ?order=popular ?order=recent
GET http://localhost:8086/api/v1/posts?order=recent

### GET BY SLUG
GET http://localhost:8086/api/v1/posts/5525840-post-created-user-1

### UPVOTE/DOWNVOTE /upvote /downvote
POST http://localhost:8086/api/v1/posts/5525840-post-created-user-1/downvote

### CREATE ONE
POST http://localhost:8086/api/v1/posts/
Content-Type: application/json

{
    "title": "POST CREATED USER 1",
    "text": "Text post",
    "type": "text"
}

