### UPVOTE/DOWNVOTE /upvote /downvote
POST http://localhost:8086/api/v1/posts/6482851-post-created-user-1/upvote

### CREATE ONE
POST http://localhost:8086/api/v1/posts/
Content-Type: application/json

{
    "title": "POST CREATED USER 1",
    "text": "Text post",
    "type": "text"
}

