export const MEMBER_TYPES = {
  MAPPER: Symbol('MEMBER_MAPPER'),
  QUERY_MAPPER: Symbol('MEMBER_QUERY_MAPPER'),
  REPOSITORY: Symbol('MEMBER_REPOSITORY'),
  QUERY_REPOSITORY: Symbol('MEMBER_QUERY_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol('MEMBER_SEQUELIZE_MODEL'),
  SEQUELIZE_ROLE_MODEL: Symbol.for('MEMBER_SEQUELIZE_ROLE_MODEL'),
}
