export const MEMBER_TYPES = {
  MAPPER: Symbol('MEMBER_MAPPER'),
  QUERY_MAPPER: Symbol('QUERY_MAPPER'),
  REPOSITORY: Symbol('MEMBER_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol('MEMBER_SEQUELIZE_MODEL'),
}
