const POST_TYPES = {
  MAPPER: Symbol.for('POST_MAPPER'),
  REPOSITORY: Symbol.for('POST_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol.for('POST_SEQUELIZE_MODEL'),
}

const POST_VOTE_TYPES = {
  MAPPER: Symbol.for('POST_VOTE_MAPPER'),
  REPOSITORY: Symbol.for('POST_VOTE_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol.for('POST_VOTE_SEQUELIZE_MODEL'),
}

export { POST_TYPES, POST_VOTE_TYPES }
