const USER_TYPES = {
  MAPPER: Symbol.for('USER_MAPPER'),
  QUERY_MAPPER: Symbol('COMMENT_QUERY_MAPPER'),
  REPOSITORY: Symbol.for('USER_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol.for('USER_SEQUELIZE_MODEL'),
  AUTH_SERVICE: Symbol.for('AUTH_SERVICE'),
}

export { USER_TYPES }
