const USER_TYPES = {
  ROUTER: Symbol.for('USER_ROUTER'),
  MAPPER: Symbol.for('USER_MAPPER'),
  REPOSITORY: Symbol.for('USER_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol.for('USER_SEQUELIZE_MODEL'),
  AUTH_SERVICE: Symbol.for('AUTH_SERVICE'),
}

export { USER_TYPES }
