export const POST_TYPES = {
  MAPPER: Symbol('POST_MAPPER'),
  QUERY_MAPPER: Symbol('POST_QUERY_MAPPER'),
  REPOSITORY: Symbol('POST_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol('POST_SEQUELIZE_MODEL'),
}
