### LOGIN
POST http://localhost:8086/api/v1/users/login
Content-Type: application/json

{
    "login": "victor",
    "password": "12345678"
}

### LOGOUT
POST http://localhost:8086/api/v1/users/logout


### CREATE ONE
POST http://localhost:8086/api/v1/users/
Content-Type: application/json

{
    "login": "member-11211",
    "email": "member-1111111111111111@gmail.com",
    "password": "12345678"
}

### CURRENT USER
GET http://localhost:8086/api/v1/users/currentUser

### REFRESH TOKEN
POST http://localhost:8086/api/v1/users/refreshToken
Content-Type: application/json

{
    "refreshToken": "8e02872d-d32b-464b-a25a-8a6f4cbdabd2"
}

