
### GET LIST
GET http://localhost:8086/api/v1/users


### GET BY LOGIN
GET http://localhost:8086/api/v1/users/vitalii

### DELETE BY LOGIN
DELETE http://localhost:8086/api/v1/users/member-1

### LOGIN
POST http://localhost:8086/api/v1/users/login
Content-Type: application/json

{
    "login": "vitalii",
    "password": "12345678"
}

### LOGOUT
POST http://localhost:8086/api/v1/users/logout


### CREATE ONE
POST http://localhost:8086/api/v1/users/
Content-Type: application/json

{
    "login": "member-11211",
    "email": "member-1111111111111111@gmail.com",
    "password": "12345678"
}

### CURRENT USER
GET http://localhost:8086/api/v1/users/currentUser

### REFRESH TOKEN
POST http://localhost:8086/api/v1/users/refreshToken
Content-Type: application/json

{
    "refreshToken": "5950dd1c-d1d3-46f7-bd2a-ee96c4301aee"
}

