
### GET LIST
GET http://localhost:8086/api/v1/users


### GET BY ID
GET http://localhost:8086/api/v1/users/11111111-1111-1111-1111-11111111111

### DELETE BY ID
DELETE http://localhost:8086/api/v1/users/11111111-1111-1111-1111-111111111111

### RECOBER BY ID
PATCH http://localhost:8086/api/v1/users/11111111-1111-1111-1111-111111111111

### LOGIN
POST http://localhost:8086/api/v1/users/login
Content-Type: application/json

{
    "email": "vitalii@gmail.com",
    "password": "12345"
}

### LOGOUT
POST http://localhost:8086/api/v1/users/logout


### CREATE ONE
POST http://localhost:8086/api/v1/users/
Content-Type: application/json

{
    "email": "vitalii@gmail.com",
    "password": "12345"
}

### CURRENT USER
GET http://localhost:8086/api/v1/users/currentUser

### REFRESH TOKEN
POST http://localhost:8086/api/v1/users/refreshToken
Content-Type: application/json

{
    "refreshToken": "1c42db73-64cd-402d-845c-0300108b51e0"
}

