export const COMMENT_TYPES = {
  MAPPER: Symbol('COMMENT_MAPPER'),
  QUERY_MAPPER: Symbol('COMMENT_QUERY_MAPPER'),
  REPOSITORY: Symbol('COMMENT_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol('COMMENT_SEQUELIZE_MODEL'),
}
