const USER_TYPES = {
  ROUTER: Symbol.for('USER_ROUTER'),
  MAPPER: Symbol.for('USER_MAPPER'),
  REPOSITORY: Symbol.for('USER_REPOSITORY'),
  SEQUELIZE_MODEL: Symbol.for('USER_SEQUELIZE_MODEL'),
  AUTH_SERVICE: Symbol.for('AUTH_SERVICE'),

  // FIND_LIST_CONTROLLER: Symbol.for('FIND_LIST_CONTROLLER'),
  FIND_LIST_SERVICE: Symbol.for('FIND_LIST_SERVICE'),

  // FIND_USER_CONTROLLER: Symbol.for('FIND_USER_CONTROLLER'),
  // FIND_USER_SERVICE: Symbol.for('FIND_USER_SERVICE'),

  // CREATE_USER_CONTROLLER: Symbol.for('CREATE_USER_CONTROLLER'),
  // CREATE_USER_SERVICE: Symbol.for('CREATE_USER_SERVICE'),

  // UPDATE_USER_CONTROLLER: Symbol.for('UPDATE_USER_CONTROLLER'),
  // UPDATE_USER_SERVICE: Symbol.for('UPDATE_USER_SERVICE'),

  // DELETE_USER_CONTROLLER: Symbol.for('DELETE_USER_CONTROLLER'),
  // DELETE_USER_SERVICE: Symbol.for('DELETE_USER_SERVICE'),
}

export { USER_TYPES }
